Repository ocaml/setup-ocaml, pull requests merged in 2024-06, with the labels that each got.

#794 Add initial support for opam 2.2 on Windows
  .github/workflows/workflow.yml
  CHANGELOG.md
  EXAMPLES.md
  README.md
  action.yml
  analysis/dist/index.js
  biome.json
  dist/LICENSE.txt
  dist/index.js
  dist/post/LICENSE.txt
  dist/post/index.js
  lint-doc/dist/index.js
  lint-fmt/dist/index.js
  lint-opam/dist/index.js
  packages/analysis/package.json
  packages/analysis/src/analysis.ts
  packages/analysis/src/index.ts
  packages/analysis/src/opam.ts
  packages/analysis/tsconfig.json
  packages/lint-doc/package.json
  packages/lint-doc/src/index.ts
  packages/lint-doc/src/odoc.ts
  packages/lint-doc/src/opam.ts
  packages/lint-doc/tsconfig.json
  packages/lint-fmt/package.json
  packages/lint-fmt/src/index.ts
  packages/lint-fmt/src/ocamlformat.ts
  packages/lint-fmt/tsconfig.json
  packages/lint-opam/package.json
  packages/lint-opam/src/index.ts
  packages/lint-opam/src/opam.ts
  packages/lint-opam/tsconfig.json
  packages/setup-ocaml/README.md
  packages/setup-ocaml/package.json
  packages/setup-ocaml/src/cache.ts
  packages/setup-ocaml/src/constants.ts
  packages/setup-ocaml/src/depext.ts
  packages/setup-ocaml/src/dune.ts
  packages/setup-ocaml/src/index.ts
  packages/setup-ocaml/src/installer.ts
  packages/setup-ocaml/src/opam.ts
  packages/setup-ocaml/src/packages.ts
  packages/setup-ocaml/src/post.ts
  packages/setup-ocaml/src/system.ts
  packages/setup-ocaml/src/unix.ts
  packages/setup-ocaml/src/version.ts
  packages/setup-ocaml/src/win32.ts
  packages/setup-ocaml/src/windows.ts
  packages/setup-ocaml/tsconfig.json
  yarn.lock
Labels: enhancement

#814 Update doc for `opam-repositories`
  README.md
  action.yml
  dist/index.js
  dist/post/index.js
  packages/setup-ocaml/src/constants.ts
Labels: documentation

#817 Always set-up Cygwin whether or not the cache is hit
  CHANGELOG.md
  dist/index.js
  packages/setup-ocaml/src/installer.ts
Labels: bug
